version: '3.4'

networks:
  grafana:

services:
  influxdb:
    image: influxdb:2.0
    #    entrypoint: /bin/sh
    #    user: root
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=cypress
  grafana:
    image: grafana/grafana:8.5.21
    #    entrypoint: /bin/sh
    #    user: root
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    # volumes:
    #   - ./dashboards:/var/lib/grafana/dashboards
    #   - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    #   - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
