name: Cypress_AutomationTest_IMDB

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install
        run: npm install

      - name: Test run
        run: npm run test:ed && npm run allure && npm run allure-notify
      - name: Output test results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: mochawesome-report
          retention-days: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: mochawesome-report
